name: Development tools workflow
on:
  pull_request:
    types:
      - unlabeled
      - labeled
      - synchronize
      - opened
      - reopened
    paths-ignore:
      - '.gitignore'
      - '.metadata'
      - '.github/**'
      - 'README.md'
jobs:
  bump-version:
    name: Bump application version using PR labels
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version
        uses: apomalyn/bump-version-using-labels@1.3.1
        with:
          file_path: 'pubspec.yaml'
          reference_branch: 'main'